version: '3.9'
services:
  nginx:
    container_name: nginx
    image: altriabot/nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/http.conf.d:/etc/nginx/http.conf.d
      - ./nginx/stream.conf.d:/etc/nginx/stream.conf.d
      - ./nginx/html:/etc/nginx/html
      - ./logs/nginx:/var/log/nginx
      - ./nginx/cert:/etc/nginx/cert
    networks:
      - default
  xray:
    restart: always
    image: teddysun/xray
    container_name: xray
    ports:
      - 433:443
    volumes:
      - ./xray:/etc/xray
      - ./logs/xray:/var/log/xray
    depends_on:
      - nginx
    networks:
      - default
networks:
  default:
      driver: web